on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Update super-dataset
    steps:
      - name: "Update TemplateFlow's superdataset"
        uses: templateflow/actions-template@main
        env:
          SECRET_KEY: ${{ secrets.NIPREPS_BOT }}

