on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: "Update TemplateFlow's superdataset"
        id: superdataset
        uses: templateflow/actions-template@main
        env:
          SECRET_KEY: ${{ secrets.TEST_SECRET }}

