on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: templateflow/actions-template@v0.0.1
        with:
          ssh-private-key: testkey

