on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Update super-dataset
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: nipreps-bot
          password: ${{ secrets.NIPREPS_BOT_PAT }}
          
      - name: "Update TemplateFlow's superdataset"
        uses: templateflow/actions-template@main
        env:
          SECRET_KEY: ${{ secrets.NIPREPS_BOT }}

